name: app_templates
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.1.4
  get_storage: ^2.0.2
  country_code_picker: ^2.0.1
  community_material_icon: ^5.9.55
  pin_code_fields: ^7.2.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/png/
    - assets/images/gif/
    - assets/images/icon-png/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
    - family: Bayon
      fonts:
        - asset: assets/fonts/Bayon/Bayon-Regular.ttf
    - family: Preahvihear
      fonts:
        - asset: assets/fonts/Preahvihear/Preahvihear-Regular.ttf
    - family: Battambang
      fonts:
        - asset: assets/fonts/Battambang/Battambang-Regular.ttf
        - asset: assets/fonts/Battambang/Battambang-Bold.ttf
